### ISSUE TITLE
Auktorisering bug

### ISSUE THREAD

**Issue by fjohansson92** [SheriefBadran/EasyActApiHandler#1]
Du har missat att testa om en användare är admin i AdminboardController, alla användare kan därför lista alla användare och ta bort användare.

**Comment by SheriefBadran** [comment]
Aj då, inte bra.. det ska jag kolla upp och lösa! Tack!

**Comment by 1dv450** [comment]
:+1:  Får fixas och stäng denna issue när det är gjort.
