### ISSUE TITLE
Utloggning är osäker

### ISSUE THREAD

**Issue by ib222dp** [SheriefBadran/EasyActApiHandler#6]
Om man efter att man loggat ut trycker på webbläsarens Tillbaka-knapp kommer man tillbaka till den inloggade sidan. Jag löste detta i min applikation genom att lägga till 
 before_action :set_no_cache, 
def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
i application-controller, samt genom att lägga till "data: {no_turbolink: true}" sist i Logga ut-länkarna i mina views.

**Comment by SheriefBadran** [comment]
Stort tack för hjälpen! Fixat
